name: Auto Build

on:
  workflow_dispatch:
    # inputs:
    #   tags:
    #     description: 'Docker Tag'
    #     required: false
    #     default: 'latest'
  push:
    branches: [main, master]
    # Only build when files in these directories have been changed
    paths:
      - containers/**
      - template/**
  schedule:
    - cron:  '0 9 * * *' # UTC

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Login to ghcr.io
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Images to ghcr.io
      run: ./bin/01-build-images push
      env:
        CI_REGISTRY_IMAGE: ghcr.io/anon-123456789/terraria-server
  clean:
    runs-on: ubuntu-latest
    name: Delete old images
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ github.event.repository.name }}
          image-tags: "!latest"  # target any image that has a tag starting with the word test or dev
          cut-off: 2w
          dry-run: false
    needs: build